name: app_passo
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  board_datetime_picker: ^2.4.1

  cupertino_icons: ^1.0.8
  intl: ^0.17.0
  numberpicker: ^2.1.2
  provider: ^6.1.2
  audioplayers: ^6.1.1
  shared_preferences: ^2.5.1
  lottie: ^3.3.1
  slide_to_act: ^2.0.2
  video_player: ^2.9.2
  vibration: ^3.1.2
  weather: ^3.1.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  http: ^1.3.0
  fl_chart: ^0.70.2
  iconly: ^1.0.1
  google_fonts: ^6.2.1
  flutter_bloc: ^9.0.0
  google_generative_ai: ^0.4.6
  flutter_markdown: ^0.7.6+2
  local_auth: ^2.3.0
  speech_to_text: ^7.0.0
  google_maps_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: JosefinSans-Bold
      fonts:
        - asset: fonts/JosefinSans-Bold.ttf

    - family: JosefinSans-Light
      fonts:
        - asset: fonts/JosefinSans-Light.ttf

    - family: JosefinSans-Medium
      fonts:
        - asset: fonts/JosefinSans-Medium.ttf

    - family: JosefinSans-Regular
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf

    - family: JosefinSans-SemiBold
      fonts:
        - asset: fonts/JosefinSans-SemiBold.ttf

    - family: JosefinSans-Thin
      fonts:
        - asset: fonts/JosefinSans-Thin.ttf

  assets:
    - assets/agregarAlarma.png
    - assets/alarma.json
    - assets/add_alarm.json
    - assets/check.json
    - assets/Cascada.mp3
    - assets/lluvia.mp3
    - assets/olas_de_mar.mp3
    - assets/pajaros.mp3
    - assets/lluvia_relajacion.mp3
    - assets/fondo.json
    - assets/sol.json
    - assets/lluvia.json
    - assets/nube.json
    - assets/lluvia_chill.json
    - assets/clima_load.json
    - assets/nube_sol.json
    - assets/flags/argentina.png
    - assets/flags/bolivia.png
    - assets/flags/brasil.png
    - assets/flags/chile.png
    - assets/flags/colombia.png
    - assets/flags/costa_rica.png
    - assets/flags/cuba.png
    - assets/flags/ecuador.png
    - assets/flags/espana.png
    - assets/flags/guatemala.png
    - assets/flags/honduras.png
    - assets/flags/mexico.png
    - assets/flags/nicaragua.png
    - assets/flags/paraguay.png
    - assets/flags/peru.png
    - assets/flags/puerto_rico.png
    - assets/flags/salvador.png
    - assets/flags/uruguay.png
    - assets/flags/venezuela.png
    - assets/flags/estados_unidos.png
    - assets/flags/canada.png
    - assets/flags/inglaterra.png
    - assets/flags/italia.png
    - assets/flags/alemania.png
    - assets/flags/francia.png
    - assets/flags/portugal.png
    - assets/flags/irlanda.png
    - assets/flags/escocia.png
    - assets/flags/afghanistan.png
    - assets/flags/albania.png
    - assets/flags/andorra.png
    - assets/flags/angola.png
    - assets/flags/arabia_saudita.png
    - assets/flags/argelia.png
    - assets/flags/armenia.png
    - assets/flags/australia.png
    - assets/flags/austria.png
    - assets/flags/bangladesh.png
    - assets/flags/belgica.png
    - assets/flags/gales.png
    - assets/flags/bosnia.png
    - assets/flags/suiza.png
    - assets/flags/venezuela.png
    - assets/flags/taiwan.png
    - assets/flags/vietnam.png
    - assets/flags/grecia.png
    - assets/flags/senegal.png
    - assets/flags/costa_rica.png
    - assets/flags/serbia.png
    - assets/flags/estados_unidos.png
    - assets/flags/estonia.png
    - assets/flags/finlandia.png
    - assets/flags/francia.png
    - assets/flags/sudan.png
    - assets/flags/samoa.png
    - assets/flags/republica_cheka.png
    - assets/flags/indonesia.png
    - assets/flags/iran.png
    - assets/flags/irlanda.png
    - assets/flags/islandia.png
    - assets/flags/japon.png
    - assets/flags/iraq.png
    - assets/flags/nueva_zelanda.png
    - assets/flags/rumania.png
    - assets/flags/croacia.png
    - assets/flags/dominicana.png
    - assets/flags/albania.png
    - assets/flags/austria.png
    - assets/flags/serbia.png
    - assets/flags/slovakia.png
    - assets/flags/suecia.png
    - assets/flags/luxemburgo.png
    - assets/flags/malta.png
    - assets/flags/mali.png
    - assets/flags/marruecos.png
    - assets/flags/pakistan.png
    - assets/flags/netherlands.png
    - assets/flags/panama.png
    - assets/flags/rusia.png
    - assets/flags/turquia.png
    - assets/flags/fiji.png
    - assets/flags/gran_bretaña.png
    - assets/flags/noruega.png
    - assets/flags/mexico.png
    - assets/flags/georgia.png
    - assets/flags/nigeria.png
    - assets/flags/palestina.png
    - assets/flags/polonia.png
    - assets/flags/qatar.png
    - assets/flags/sudafrica.png
    - assets/flags/ucrania.png
    - assets/flags/uganda.png
    - assets/flags/yemen.png

  uses-material-design: true
