name: app_passo
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  board_datetime_picker: ^2.4.1

  cupertino_icons: ^1.0.8
  intl: ^0.17.0
  numberpicker: ^2.1.2
  provider: ^6.1.2
  audioplayers: ^6.1.1
  shared_preferences: ^2.5.1
  lottie: ^3.3.1
  slide_to_act: ^2.0.2
  video_player: ^2.9.2
  vibration: ^3.1.2
  weather: ^3.1.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  http: ^1.3.0
  fl_chart: ^0.70.2
  iconly: ^1.0.1
  google_fonts: ^6.2.1
  flutter_bloc: ^9.0.0
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: JosefinSans-Bold
      fonts:
        - asset: fonts/JosefinSans-Bold.ttf

    - family: JosefinSans-Light
      fonts:
        - asset: fonts/JosefinSans-Light.ttf

    - family: JosefinSans-Medium
      fonts:
        - asset: fonts/JosefinSans-Medium.ttf

    - family: JosefinSans-Regular
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf

    - family: JosefinSans-SemiBold
      fonts:
        - asset: fonts/JosefinSans-SemiBold.ttf

    - family: JosefinSans-Thin
      fonts:
        - asset: fonts/JosefinSans-Thin.ttf

  assets:
    - assets/agregarAlarma.png
    - assets/alarma.json
    - assets/add_alarm.json
    - assets/check.json
    - assets/Cascada.mp3
    - assets/lluvia.mp3
    - assets/olas_de_mar.mp3
    - assets/pajaros.mp3
    - assets/lluvia_relajacion.mp3
    - assets/fondo.json
    - assets/sol.json
    - assets/lluvia.json
    - assets/nube.json
    - assets/lluvia_chill.json
    - assets/clima_load.json
    - assets/nube_sol.json

  uses-material-design: true
